basePath: /api
definitions:
  main.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: import-swag-api
  version: "1.0"
paths:
  /users:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
      summary: Get all users
      tags:
      - users
swagger: "2.0"
